apiVersion: v1
kind: Service
metadata:
  name: pmlog-service
  namespace: pm-logging
spec:
  selector:
    app: pmlog
  ports:
    - protocol: TCP
      port: 8184
      targetPort: 8084
    - protocol: TCP
      port: 8436
      targetPort: 8436
  type: ClusterIP

