apiVersion: v1
kind: PersistentVolume
metadata:
  name: pm-token-cache-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/pm-token-cache"  # Adjust based on your setup

